// autoFares.js
// Main dataset: Kolkata local auto/rickshaw point-to-point fares
// Cross-referenced against stop names extracted from the routes1 bus dataset (auto_live project)
//
// HONESTY NOTE:
// Per-route fares below are exactly as supplied in the original source list.
// A web search found no centralized, route-by-route public price list for Kolkata's
// informal SHARED auto-rickshaws (fares are set locally per route, not gazetted).
// The one verifiable figure is the official government CNG auto tariff FORMULA
// (for metered/reserved rides), included below as `officialTariff`, current as of Feb 2025.
// fromMatchedBusStop / toMatchedBusStop cross-reference each endpoint against the
// actual stop names appearing in the routes1 bus-route dataset (272 unique stops extracted).

const officialTariff = {
  "effective_from": "2025-02-01",
  "note_source": "West Bengal / regional CNG auto-rickshaw tariff card, as reported Feb 2025",
  "minimum_fare_inr": 26.0,
  "per_km_inr": 17.14,
  "night_surcharge_percent": 25,
  "night_hours": "00:00-05:00",
  "caveat": "This is the metered/reserved-auto tariff formula. Kolkata's point-to-point SHARED autos (the kind in this dataset) run on fixed, route-specific, per-seat fares set informally/locally and are NOT centrally published online route-by-route, so individual route fares below cannot be verified against a government source. Distances per route are unknown, so no automatic per-route estimate is computed -- the formula is provided only as a manual sanity-check reference."
};

function estimateFare(distanceKm) {
  if (typeof distanceKm !== 'number' || distanceKm < 0) return null;
  const raw = officialTariff.minimum_fare_inr + distanceKm * officialTariff.per_km_inr;
  return Math.round(raw);
}

// 272 unique stop names extracted from the routes1 bus dataset
const busRouteStops = [
  "Acropolis Mall",
  "Ahiritola",
  "Airport 1no.",
  "Airport 3no.",
  "Ajaynagar",
  "Alampur",
  "Alipore Court",
  "Alipore Zoo",
  "Amta",
  "Anandapur",
  "Ankurhati",
  "Anwar Shah Road",
  "Arapanch",
  "Ashubabu Bazar",
  "BBD Bag",
  "BK Paul More",
  "BNR Hospital",
  "BT College",
  "Babubazar",
  "Babughat",
  "Badartala",
  "Badir More",
  "Bagbazar",
  "Baghajatin",
  "Baguiati",
  "Baisakhi More",
  "Ballygunge Phari",
  "Ballygunge Station",
  "Baltikuri",
  "Bandel",
  "Bandha Ghat",
  "Baneshwarpur",
  "Bangur Avenue",
  "Bankra Bazar",
  "Bansbhberia",
  "Bansdroni",
  "Barabazar",
  "Barasat Chapadali More",
  "Barrackpore Chiria More",
  "Barrackpore Court",
  "Beckbagan",
  "Behala 14no.",
  "Behala Chowrasta",
  "Belgachi",
  "Belgachia",
  "Bhabani Bhawan",
  "Bhawani Bhawan",
  "Bhowanipore",
  "Bibibazar",
  "Bichali Ghat",
  "Bikash Bhawan",
  "Birati More",
  "Bodra",
  "Bonhooghly",
  "Boropara",
  "Bosepukur",
  "Brace Bridge",
  "Central Jail",
  "Central Metro",
  "Chakberia",
  "Chandaneshwar",
  "Chandni Market",
  "Chetla Park",
  "Chinsurah Court",
  "Chiria More",
  "Chitpur Bridge",
  "Christopher Road",
  "City Center 1",
  "College More",
  "College Street",
  "Companir Thek",
  "Cossipur",
  "Dalalpukur",
  "Dalanghata",
  "Dalhousie",
  "Dasnagar",
  "Deshapriya Park",
  "Deular More",
  "Dhakuria",
  "Dhulagarh",
  "Diamond Harbour",
  "Diamond Plaza",
  "Dihibhursut",
  "Dumdum Park",
  "Dumdum Station",
  "Dumurdaha",
  "Dunlop More",
  "Durgapur Bridge",
  "EM Bypass",
  "Eden Gardens",
  "Ekbalpur",
  "Esplanade",
  "Fort William",
  "Garden Reach",
  "Garh Bhowanipore",
  "Garia Bus Stand",
  "Garia Metro",
  "Garia Station",
  "Gariahat",
  "Ghasiara",
  "Ghatakpukur",
  "Ghorir More",
  "Girish Park",
  "Golabarai PS",
  "Golpark",
  "Gouripur",
  "Gurusaday Road",
  "Haldirams",
  "Haltu Bazar",
  "Hastings",
  "Hatibagan",
  "Hatikanda",
  "Hatugunge",
  "Hazra More",
  "Hide Road",
  "Hooghly More",
  "Howrah Maidan",
  "Howrah Station",
  "Jadavpur 8B",
  "Jagulgachi",
  "Jalan Gate",
  "Japani Gate",
  "Jhautala",
  "Jhinjhira Bazar",
  "Jirat",
  "Jorabagan",
  "Kaikhali",
  "Kalibabu Bazar",
  "Kalighat",
  "Kalikapur",
  "Kalindi More",
  "Kalitala",
  "Kamal Talkies",
  "Kamalpur",
  "Kamarhati",
  "Kankurgachi",
  "Karbala More",
  "Karunamoyee",
  "Kasba PS",
  "Kasba Post Office",
  "Kashinagar",
  "Keota",
  "Kestopur",
  "Khadina More",
  "Khanna Cinema",
  "Khardah",
  "Khidderpore",
  "Khirishtala",
  "Khotirbazar",
  "Krishnachandrapur",
  "Kuntighat",
  "Lake Gardens",
  "Laketown",
  "Lalpur",
  "MG Road",
  "ML Gupta Road",
  "Madhyamgram",
  "Mahabirtala",
  "Maidan Metro",
  "Majherhat",
  "Makrampur",
  "Malancha Cinema",
  "Malapara",
  "Mallick Fatak",
  "Mandirbazar",
  "Maniktala",
  "Mathurapur Station",
  "Mayramahal",
  "Mearbere More",
  "Medical College",
  "Metiabruz",
  "Milk Colony",
  "Minto Park",
  "Mominpore",
  "Moulali More",
  "Muchipara",
  "Mukundapur",
  "Nagerbazar",
  "Naktala",
  "Natagachi",
  "Natun Rasta",
  "Nature Park",
  "Nayabad",
  "Netaji Nagar",
  "New Alipore",
  "New Garia",
  "Nibra More",
  "Nimtala",
  "Noapara",
  "PTS More",
  "Palmer Bazar",
  "Panchkari More",
  "Panpur More",
  "Park Street",
  "Patipukur",
  "Patkelpota",
  "Peerless Hospital",
  "Phoolbagan",
  "Pilkhana More",
  "Prasadpur",
  "Princep Ghat",
  "Pukuria Hat",
  "RG Kar Hospital",
  "RN Chowdhury Road",
  "Rabindra Sadan",
  "Rabindra Sarovar",
  "Raidighi",
  "Rajabagan",
  "Rajabazar",
  "Rajballavpara",
  "Ramchandrapur",
  "Ramgarh",
  "Ramlal Bazar",
  "Ramnagar",
  "Ramrajatala",
  "Ranihati",
  "Ranikuthi",
  "Rashbehari",
  "Rathtala More",
  "Ratneshwarpur",
  "Ruby Hospital",
  "SDF More",
  "Sahagunj",
  "Saihati",
  "Sakher Bazar",
  "Salap More",
  "Salkia Chowrasta",
  "Saltlake 206",
  "Saltlake 4no. Tank",
  "Saltlake 7no. Tank",
  "Saltlake 9no. Tank",
  "Saltlake C.A. Block",
  "Saltlake PNB",
  "Sanksaharpukur",
  "Santoshpur",
  "Sapuipara",
  "Sealdah Station",
  "Sector V",
  "Sehagori",
  "Shanpur More",
  "Shyamasree",
  "Shyambazar",
  "Sinthee More",
  "Siriti More",
  "Situri",
  "Sobedatala",
  "Sodepur Girja",
  "Sonarpur",
  "Sondalia Bablatala",
  "South Bishnupur",
  "South City",
  "Southern Avenue",
  "Sovabazar",
  "Sreebhumi",
  "Sundia",
  "Surkikal",
  "Tangra More",
  "Taratala",
  "Tegharia",
  "Tematha",
  "Tikiapara Bypass",
  "Titagarh",
  "Tobin Road",
  "Tollygunge Metro",
  "Tollygunge Phari",
  "Topsia More",
  "Tribeni",
  "Udaynarayanpur",
  "Ultadanga",
  "Vivekananda Road",
  "Wellington",
  "Wipro More"
];

// Main dataset: auto/rickshaw fares
const autoFares = [
  {
    id: 1,
    from: "Ahiritola Launch Ghat",
    to: "Beadon Street A.P.C. Road Crossing",
    via: ["Beadon Street"],
    fareINR: 70,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ahiritola",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 2,
    from: "Ahiritola Launch Ghat",
    to: "Ultadanga Station",
    via: ["Ahiritola St.", "B.K. Pal Avenue", "Aurobindo Setu"],
    fareINR: 195,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ahiritola",
    toMatchedBusStop: "Ultadanga",
    flag: null
  },
  {
    id: 3,
    from: "Ahiritola",
    to: "Maniktala (Bidhan Sarani A.P.C. Road Crossing)",
    via: [],
    fareINR: 70,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ahiritola",
    toMatchedBusStop: "Maniktala",
    flag: null
  },
  {
    id: 4,
    from: "Alipore Judge Court",
    to: "Ballygunge Station",
    via: ["Gopal Nagar", "Kalighat Bridge", "Hazra", "S.P. Mukherjee Road", "R.B. Avenue", "Gariahat"],
    fareINR: 105,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Ballygunge Station",
    flag: null
  },
  {
    id: 5,
    from: "Akra Fatak",
    to: "Santoshpur",
    via: ["Santoshpur Road (Ghosh Para)"],
    fareINR: 50,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Santoshpur",
    flag: null
  },
  {
    id: 6,
    from: "Bosepukur (Gariahat)",
    to: "Behala",
    via: [],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Bosepukur",
    toMatchedBusStop: "Behala Chowrasta",
    flag: null
  },
  {
    id: 7,
    from: "Ballygunge Bus Stand",
    to: "Alipore Judge Court",
    via: [],
    fareINR: 120,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ballygunge Station",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 8,
    from: "Ballygunge Phari",
    to: "Picnic Garden",
    via: [],
    fareINR: 90,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ballygunge Phari",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 9,
    from: "Ballygunge Phari",
    to: "Hazra More",
    via: ["Hazra Road"],
    fareINR: 25,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ballygunge Phari",
    toMatchedBusStop: "Hazra More",
    flag: null
  },
  {
    id: 10,
    from: "Ballygunge Station",
    to: "Hazra More",
    via: [],
    fareINR: 30,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ballygunge Station",
    toMatchedBusStop: "Hazra More",
    flag: null
  },
  {
    id: 11,
    from: "B.R. Singh Hospital",
    to: "Dhapa Math Pukur",
    via: ["Beliaghata Main Road", "Pamar Bazar Crossing", "Metropolitan Co-operative Housing Society"],
    fareINR: 250,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 12,
    from: "B.R. Singh Hospital",
    to: "Baishali",
    via: ["Beliaghata Main Road"],
    fareINR: 175,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 13,
    from: "9 & 15 Bus Stand",
    to: "E.S.I. Hospital (Raja Bazar)",
    via: ["Biplabi Bankim Ghosh Sarani", "Maniktala Main Road", "Raja Dinendra Street", "Gas Street"],
    fareINR: 35,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 14,
    from: "B.K. Paul (M.G. Sarani)",
    to: "M.G. Road Rabindra Sarani (Crossing)",
    via: [],
    fareINR: 145,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "BK Paul More",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 15,
    from: "B.R. Singh Hospital",
    to: "Baman Ghata Bantala",
    via: ["Beliaghata Main Road"],
    fareINR: 65,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 16,
    from: "Bagbazar Bata",
    to: "Baghbazar Launch Ghat",
    via: ["Bagbazar Street"],
    fareINR: 20,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Bagbazar",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 17,
    from: "Bengal Chemical",
    to: "Kaizar Street",
    via: ["Maniktala Main Road", "Kankurgachi More", "C.I.T. Road", "Phool Bagan More", "Narkel Danga Main Road", "Gas Street"],
    fareINR: 100,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 18,
    from: "Cossipur 4B Bus Stand",
    to: "Paikpara 2 No. Bus Stand",
    via: ["Cossipur Road", "K.C. Road", "Chiria More", "Dum Dum Road", "Rani Harshmoyee Road"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Cossipur",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 19,
    from: "Chetla",
    to: "Gariahat",
    via: ["Chetla Central Road", "R.B. Avenue"],
    fareINR: 50,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Chetla Park",
    toMatchedBusStop: "Gariahat",
    flag: null
  },
  {
    id: 20,
    from: "Chiria More",
    to: "Dum Dum G.S. Colony",
    via: [],
    fareINR: 15,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Chiria More",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 21,
    from: "Cossipur 4B Bus Stand",
    to: "Dum Dum Station",
    via: ["K.C. Road", "Paikpara", "Dum Dum Road"],
    fareINR: 75,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Cossipur",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 22,
    from: "Cossipur 4B Bus Stand",
    to: "Sinthee More",
    via: ["Cossipur Road", "K.C. Road"],
    fareINR: 35,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Cossipur",
    toMatchedBusStop: "Sinthee More",
    flag: null
  },
  {
    id: 23,
    from: "College Street",
    to: "Shyambazar",
    via: ["M.G. Road", "Bidhan Sarani"],
    fareINR: 110,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "College Street",
    toMatchedBusStop: "Shyambazar",
    flag: null
  },
  {
    id: 24,
    from: "College Street (MG Road Crossing)",
    to: "Sealdah",
    via: ["Mahatma Gandhi Road", "B.B. Ganguly Street"],
    fareINR: 90,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "College Street",
    toMatchedBusStop: "Sealdah Station",
    flag: null
  },
  {
    id: 25,
    from: "Cornfield Road (Ballygunge Phari)",
    to: "Deshapriya Park",
    via: ["Rash Behari Avenue"],
    fareINR: 30,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ballygunge Phari",
    toMatchedBusStop: "Deshapriya Park",
    flag: null
  },
  {
    id: 26,
    from: "Dum Dum Station",
    to: "Shyambazar",
    via: ["Dum Dum Road", "B.T. Road"],
    fareINR: 200,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Shyambazar",
    flag: null
  },
  {
    id: 27,
    from: "Deshapriya Park",
    to: "Kalighat Metro Station",
    via: ["Rash Behari Avenue", "Kalighat Road"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Deshapriya Park",
    toMatchedBusStop: "Kalighat",
    flag: null
  },
  {
    id: 28,
    from: "Dhapa Math Pukur",
    to: "Science City",
    via: ["Math Pukur Road", "E.M. Bye Pass"],
    fareINR: 40,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 29,
    from: "Dhapa Math Pukur",
    to: "Beliaghata Main Road",
    via: [],
    fareINR: 20,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 30,
    from: "Dhapa Road",
    to: "Topsia Road (South)",
    via: [],
    fareINR: 30,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Topsia More",
    flag: null
  },
  {
    id: 31,
    from: "Deshapriya Park",
    to: "Kalighat Bridge",
    via: ["Sarat Bose Road"],
    fareINR: 25,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Deshapriya Park",
    toMatchedBusStop: "Kalighat",
    flag: null
  },
  {
    id: 32,
    from: "Deshapriya Park",
    to: "Hazra More",
    via: ["Hazra Road"],
    fareINR: 20,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Deshapriya Park",
    toMatchedBusStop: "Hazra More",
    flag: null
  },
  {
    id: 33,
    from: "Deshapriya Park",
    to: "Southern Avenue",
    via: [],
    fareINR: 15,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Deshapriya Park",
    toMatchedBusStop: "Southern Avenue",
    flag: null
  },
  {
    id: 34,
    from: "Dhapa Road",
    to: "Park Circus 4 Point Crossing",
    via: ["Topsia Road", "Topsia Road (South)"],
    fareINR: 50,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Park Street",
    flag: null
  },
  {
    id: 35,
    from: "Dum Dum Station",
    to: "Belgachia",
    via: ["Dum Dum Road", "B.T. Road"],
    fareINR: 125,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Belgachia",
    flag: null
  },
  {
    id: 36,
    from: "Dum Dum Station",
    to: "Nagerbazar",
    via: ["Jessore Road"],
    fareINR: 140,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Nagerbazar",
    flag: null
  },
  {
    id: 37,
    from: "Dum Dum Station",
    to: "Chiria More",
    via: ["Dum Dum Road"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Chiria More",
    flag: null
  },
  {
    id: 38,
    from: "Dum Dum Station",
    to: "Paikpara 2 No. Bus Stand",
    via: ["Dum Dum Road", "Rani Harshmoyee Road"],
    fareINR: 45,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 39,
    from: "Dum Dum Station",
    to: "Cossipur 4B Bus Stand",
    via: ["K.C. Road"],
    fareINR: 40,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Cossipur",
    flag: null
  },
  {
    id: 40,
    from: "Dum Dum Station",
    to: "Sinthi More",
    via: ["Sinthi Main Road"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 41,
    from: "Dum Dum Station",
    to: "Sarat Colony",
    via: ["Jessore Road"],
    fareINR: 25,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 42,
    from: "E.M. Bye Pass (Ajaynagar Crossing)",
    to: "Garia",
    via: ["E.M. Bye Pass", "Patuli"],
    fareINR: 35,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ajaynagar",
    toMatchedBusStop: "Garia Station",
    flag: null
  },
  {
    id: 43,
    from: "Esplanade Bus Stand",
    to: "Howrah Station",
    via: ["Strand Road", "Howrah Bridge"],
    fareINR: 175,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Esplanade",
    toMatchedBusStop: "Howrah Station",
    flag: null
  },
  {
    id: 44,
    from: "Esplanade Bus Stand",
    to: "Sealdah Station",
    via: ["R.N. Mukherjee Road", "B.B. Ganguly Street"],
    fareINR: 160,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Esplanade",
    toMatchedBusStop: "Sealdah Station",
    flag: null
  },
  {
    id: 45,
    from: "Esplanade Bus Stand",
    to: "B.B.D. Bagh",
    via: ["R.N. Mukherjee Road"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Esplanade",
    toMatchedBusStop: "BBD Bag",
    flag: null
  },
  {
    id: 46,
    from: "Esplanade Bus Stand",
    to: "Park Street",
    via: ["Chowringhee Road"],
    fareINR: 75,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Esplanade",
    toMatchedBusStop: "Park Street",
    flag: null
  },
  {
    id: 47,
    from: "Esplanade Bus Stand",
    to: "Maidan",
    via: ["Red Road"],
    fareINR: 50,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Esplanade",
    toMatchedBusStop: "Howrah Maidan",
    flag: null
  },
  {
    id: 48,
    from: "Esplanade Bus Stand",
    to: "Lal Bazaar",
    via: ["Bentinck Street"],
    fareINR: 65,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Esplanade",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 49,
    from: "Elliot Road",
    to: "Park Circus",
    via: ["Elliot Road", "A.J.C. Bose Road"],
    fareINR: 45,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Park Street",
    flag: null
  },
  {
    id: 50,
    from: "Elliot Road",
    to: "Free School Street",
    via: [],
    fareINR: 30,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 51,
    from: "Metiabruj P.S.",
    to: "Raja Bagan Bus Stand",
    via: ["Dr. A.K. Road", "Garden Reach Road"],
    fareINR: 105,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 52,
    from: "Metiabruj (G.R.S.E Gate)",
    to: "Khidirpore Crossing (Chitrapuri Cinema)",
    via: ["Garden Reach Road", "C.G.R. Road", "Ramnagar Mudiali"],
    fareINR: 70,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 53,
    from: "Orient Row",
    to: "Dharmatala",
    via: ["Park Street", "A.J.C. Bose Road", "Elliot Road", "R.A. Kidwai Road", "S.N. Banerjee Road", "Grant Street"],
    fareINR: 35,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 54,
    from: "Phool Bagan",
    to: "Salt Lake 13 No. Tank",
    via: [],
    fareINR: 355,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 55,
    from: "Panchanantala",
    to: "Park Circus",
    via: ["Syed Amir Ali Avenue"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Park Street",
    flag: null
  },
  {
    id: 56,
    from: "Panchanantala",
    to: "4 No. Bridge",
    via: ["Broad Street"],
    fareINR: 40,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Saltlake 4no. Tank",
    flag: null
  },
  {
    id: 57,
    from: "Phool Bagan More",
    to: "CIT Building",
    via: ["Beliaghata Main Road"],
    fareINR: 15,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 58,
    from: "Phool Bagan",
    to: "Ganesh Talkies",
    via: ["Maniktala", "Bagmari", "CIT Road"],
    fareINR: 110,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 59,
    from: "Ram Nagar More",
    to: "Badar Tala",
    via: ["Kamal Talkies", "Metiabruz P.S."],
    fareINR: 420,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 60,
    from: "Not Specified",
    to: "Not Specified",
    via: [],
    fareINR: 75,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: "incomplete_record_in_source_data"
  },
  {
    id: 61,
    from: "Ram Nagar More",
    to: "Mudiali",
    via: ["Taratala Road", "Paharpur Road"],
    fareINR: 35,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 62,
    from: "Ram Nagar More",
    to: "Santoshpur",
    via: [],
    fareINR: 30,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Santoshpur",
    flag: null
  },
  {
    id: 63,
    from: "R.G. Kar Hospital",
    to: "30A Bus Stand",
    via: ["Dum Dum Road", "Belghachia Bridge", "Indra Biswas Road", "Manmath Road", "Northern Avenue"],
    fareINR: 50,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "RG Kar Hospital",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 64,
    from: "Raja Bazar (Tasbir Mahal)",
    to: "Pilkhana",
    via: ["Canal West Road"],
    fareINR: 35,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Pilkhana More",
    flag: null
  },
  {
    id: 65,
    from: "Rashbehari More (Melody)",
    to: "Behala Tram Depot",
    via: ["Chetla", "New Alipore", "Taratala"],
    fareINR: 75,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Rashbehari",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 66,
    from: "Rash Behari (Basanti Devi College)",
    to: "Behala Tram Depot",
    via: ["Rash Behari Avenue", "Chetla", "New Alipore", "Taratala"],
    fareINR: 65,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "College Street",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 67,
    from: "R.G. Kar Hospital",
    to: "Kaizar Street",
    via: ["Dinendra Street"],
    fareINR: 50,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "RG Kar Hospital",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 68,
    from: "Rashbehari Avenue",
    to: "Tollygunge Tram Depot",
    via: ["D.P.S. Road", "S.P. Mukherjee Road"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Rashbehari",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 69,
    from: "Rashbehari Avenue and Pratapaditya Road Crossing",
    to: "Chetla (Dalminya Park)",
    via: [],
    fareINR: 110,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Rashbehari",
    toMatchedBusStop: "Park Street",
    flag: null
  },
  {
    id: 70,
    from: "Ramnagar More",
    to: "Metiabruz Kanchi Sarak",
    via: [],
    fareINR: 25,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ramnagar",
    toMatchedBusStop: "Metiabruz",
    flag: null
  },
  {
    id: 71,
    from: "S.P. Mukherjee Road",
    to: "Cornfield Road",
    via: ["R.B. Avenue"],
    fareINR: 20,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 72,
    from: "Sahapur",
    to: "Tollygunge Phari",
    via: ["Sahapur Road", "T.C. Road"],
    fareINR: 30,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Tollygunge Phari",
    flag: null
  },
  {
    id: 73,
    from: "Sovabazar Launch Ghat",
    to: "Ultadanga Station",
    via: ["Stand Bank", "Sovabazar Street", "Ultadanga Main Road"],
    fareINR: 100,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Sovabazar",
    toMatchedBusStop: "Ultadanga",
    flag: null
  },
  {
    id: 74,
    from: "Sealdah Court Complex",
    to: "C.I.T. Building",
    via: ["B.M. Road"],
    fareINR: 315,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Sealdah Station",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 75,
    from: "Sealdah (Chhabi Ghar)",
    to: "Bara Bazar New Howrah Bridge Approach Road",
    via: [],
    fareINR: 225,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Sealdah Station",
    toMatchedBusStop: "Howrah Station",
    flag: null
  },
  {
    id: 76,
    from: "Tollygunge Phari",
    to: "Behala Tram Depot",
    via: ["D.C. Road", "S.P. Road", "D.H. Road"],
    fareINR: 90,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Tollygunge Phari",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 77,
    from: "Tollygunge Phari",
    to: "Jadavpur P.S.",
    via: ["P. Saha Road"],
    fareINR: 75,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Tollygunge Phari",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 78,
    from: "Tiljala",
    to: "Topsia",
    via: ["4 No. Bridge"],
    fareINR: 35,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Topsia More",
    flag: null
  },
  {
    id: 79,
    from: "Taratala",
    to: "Ram Nagar Crossing",
    via: ["Taratala Road", "New Taratala Road"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Taratala",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 80,
    from: "Taratala",
    to: "Mollar Gate",
    via: ["Taratala Road", "Budge Budge Road"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Taratala",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 81,
    from: "R.G. Hospital",
    to: "Beliaghata I.D. Hospital",
    via: ["Dinendra Street", "Manicktala P.S.", "Kankurgachi", "Phoolbagan"],
    fareINR: 130,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 82,
    from: "Ultadanga Station (P&T Qtrs.)",
    to: "Jora Bagan Power House",
    via: ["Aurobindo Sarani", "Sova Bazar", "B.K. Paul Avenue"],
    fareINR: 390,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ultadanga",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 83,
    from: "Ultadanga",
    to: "Sova Bazar",
    via: ["Aurobindo Sarani"],
    fareINR: 145,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ultadanga",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 84,
    from: "Ultadanga Station",
    to: "Salt Lake (13 No. Tank)",
    via: [],
    fareINR: 75,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ultadanga",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 85,
    from: "Ultadanga Station",
    to: "Baguihati",
    via: [],
    fareINR: 75,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ultadanga",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 86,
    from: "Ultadanga Station",
    to: "Salt Lake (Karunamayee)",
    via: [],
    fareINR: 100,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ultadanga",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 87,
    from: "Ultadanga Station",
    to: "Lake Town VIP Crossing",
    via: [],
    fareINR: 45,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Ultadanga",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 88,
    from: "Belgachia Metro",
    to: "VIP Crossing",
    via: [],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Belgachia",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 89,
    from: "Park Circus",
    to: "Bose Pukur",
    via: ["Gariahat", "Basanti Devi College", "Ramani Chatterjee Road", "Gariahat More"],
    fareINR: 65,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Park Street",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 90,
    from: "Southern Avenue / S.P.M. Road Crossing",
    to: "Garai",
    via: ["Tollygunge Tram Depot"],
    fareINR: 120,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Southern Avenue",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 91,
    from: "Southern Avenue / S.P.M. Road",
    to: "Tollygunge Tram Depot",
    via: [],
    fareINR: 45,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Southern Avenue",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 92,
    from: "Bose Pukur",
    to: "Gariahat",
    via: [],
    fareINR: 35,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Gariahat",
    flag: null
  },
  {
    id: 93,
    from: "Bag Bazar Street & Rabindra Sarani Crossing",
    to: "B.K. Paul Avenue",
    via: ["Baishnab Sett Street", "K.K. Tagore Street", "Singhgarh"],
    fareINR: 45,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "BK Paul More",
    flag: null
  },
  {
    id: 94,
    from: "Main Gate of Sports Authority of India",
    to: "Rotary Netralaya",
    via: ["K.B. Block", "K.C. Block", "Karunamayee"],
    fareINR: 65,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 95,
    from: "Kankurgachi More",
    to: "Karunamayee",
    via: [],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Kankurgachi",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 96,
    from: "Chakraberia",
    to: "Bijaygarh College",
    via: ["Padma Pukur Square", "Deshapriya Park", "Rabindra Sarobar", "Lake Gardens", "Lord's Bakery", "T.V. Centre", "17A Bus Stand"],
    fareINR: 70,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "College Street",
    flag: null
  },
  {
    id: 97,
    from: "Phool Bagan",
    to: "Karunamayee",
    via: ["Salt Lake Tank No. 13"],
    fareINR: 90,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 98,
    from: "B.K. Paul Avenue (Opposite Sova Bazar Metro Station)",
    to: "4B Bus Stand (Cossipore)",
    via: ["Raj Ballav Para", "Girish Mancha", "Cossipore Road"],
    fareINR: 85,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "BK Paul More",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 99,
    from: "Hazra Road (Khirod Ghosh Market)",
    to: "14 Bus Stand (Behala)",
    via: ["Alipore Bridge", "Rakhal Das Auddy Road", "Chetla Road", "New Alipore Petrol Pump", "Buro Shibtala", "Ray Bahadur Road"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Hazra More",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 100,
    from: "Chetla Park",
    to: "Khidirpur",
    via: ["Alipore Road", "Burdhaman Road", "D.H. Road", "Mominpore", "Kidderpore"],
    fareINR: 25,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Chetla Park",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 101,
    from: "Khiderpore",
    to: "Behala 14 No. Bus Stand",
    via: ["D.H. Road"],
    fareINR: 30,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Hide Road",
    toMatchedBusStop: "Behala 14no.",
    flag: null
  },
  {
    id: 102,
    from: "Judge Court",
    to: "Alipore Police Court",
    via: ["Judge Court Road"],
    fareINR: 20,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 103,
    from: "Chetla Park",
    to: "Behala Chowrasta",
    via: ["Mini Sanyal Sarani", "Durgapur Bridge", "Tollygunge Circular Road", "James Long Sarani"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Chetla Park",
    toMatchedBusStop: "Behala Chowrasta",
    flag: null
  },
  {
    id: 104,
    from: "Ruby General Hospital",
    to: "Jadavpore Police Station",
    via: ["Kasba Connector", "Bijan Setu", "Fern Road", "Golpark", "Dhakuria Bridge"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 105,
    from: "Dhapa",
    to: "Chitta Ranjan Hospital",
    via: ["Khal Par", "Garia Station", "Golpark", "Patuli Upanagari", "Dhalai Bridge"],
    fareINR: 70,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 106,
    from: "Garia Station",
    to: "Goalpark",
    via: ["Patuli Upanagari", "Dhalai Bridge"],
    fareINR: 125,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Garia Station",
    toMatchedBusStop: "Park Street",
    flag: null
  },
  {
    id: 107,
    from: "Tagore Park",
    to: "Circus Tram Depot",
    via: ["Picnic Garden Road", "Bondel Road", "Ballygunge Phari", "Beckbagan"],
    fareINR: 70,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Park Street",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 108,
    from: "Triangular Park",
    to: "Sakher Bazar (Behala)",
    via: ["Southern Avenue", "Menoka Cinema", "Tollygunge Rail Bridge", "Tollygunge Phari", "Tollygunge Circular Road", "James Long Sarani Chowmatha"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Park Street",
    toMatchedBusStop: "Sakher Bazar",
    flag: null
  },
  {
    id: 109,
    from: "Crossing of Pratapaditya Road (R.B. Avenue)",
    to: "Behala Chowrasta",
    via: ["Peary Mohan Roy Road", "Chetla Siding", "New Alipore Petrol Pump", "Taratala", "Pathak Para"],
    fareINR: 90,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Behala Chowrasta",
    flag: null
  },
  {
    id: 110,
    from: "Metiabruj P.S.",
    to: "Sailasri Cinema",
    via: ["Kanchi Sarak", "Paharpur Road"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 111,
    from: "Deshapriya Park",
    to: "Tollygunge Tram Depot",
    via: ["Sarat Bose Road", "Southern Avenue", "D.P. Sasmal Road", "Russa Road"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Deshapriya Park",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 112,
    from: "Ruby General Hospital",
    to: "Garia Rail Station",
    via: [],
    fareINR: 50,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Garia Station",
    flag: null
  },
  {
    id: 113,
    from: "Park Circus",
    to: "Science City",
    via: ["Beckbagan", "Topsia Road"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Park Street",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 114,
    from: "Science City",
    to: "Chingrighata",
    via: ["E.M. Bypass"],
    fareINR: 80,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 115,
    from: "Chingrighata",
    to: "Karunamayee",
    via: ["Salt Lake Sector V"],
    fareINR: 70,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 116,
    from: "Karunamayee",
    to: "College More",
    via: ["Ring Road"],
    fareINR: 40,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "College Street",
    flag: null
  },
  {
    id: 117,
    from: "College More",
    to: "Technopolis",
    via: ["Street No. 23"],
    fareINR: 35,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "College Street",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 118,
    from: "Technopolis",
    to: "New Town Action Area I",
    via: ["Major Arterial Road"],
    fareINR: 45,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 119,
    from: "New Town Action Area I",
    to: "Ecospace",
    via: ["New Town Expressway"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 120,
    from: "Ecospace",
    to: "New Town Action Area III",
    via: ["FinTech Hub", "City Centre II"],
    fareINR: 50,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 121,
    from: "New Town Action Area III",
    to: "Airport Gate 1",
    via: ["Chinar Park"],
    fareINR: 85,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 122,
    from: "Airport Gate 1",
    to: "Dumdum Metro",
    via: ["Jessore Road"],
    fareINR: 95,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Dumdum Station",
    flag: null
  },
  {
    id: 123,
    from: "Dumdum Metro",
    to: "Nagerbazar",
    via: ["B.T. Road"],
    fareINR: 80,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Dumdum Station",
    toMatchedBusStop: "Nagerbazar",
    flag: null
  },
  {
    id: 124,
    from: "Nagerbazar",
    to: "Birati",
    via: ["Jessore Road"],
    fareINR: 75,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Nagerbazar",
    toMatchedBusStop: "Birati More",
    flag: null
  },
  {
    id: 125,
    from: "Birati",
    to: "Michael Nagar",
    via: ["Jessore Road"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Birati More",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 126,
    from: "Michael Nagar",
    to: "Madhyamgram",
    via: ["Jessore Road"],
    fareINR: 65,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Madhyamgram",
    flag: null
  },
  {
    id: 127,
    from: "Madhyamgram",
    to: "Barasat Chapadali",
    via: ["Jessore Road"],
    fareINR: 100,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Madhyamgram",
    toMatchedBusStop: "Barasat Chapadali More",
    flag: null
  },
  {
    id: 128,
    from: "Barasat Chapadali",
    to: "Hridaypur",
    via: ["K.N.C. Road"],
    fareINR: 70,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Barasat Chapadali More",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 129,
    from: "Hridaypur",
    to: "Barasat Station",
    via: ["K.N.C. Road"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Barasat Chapadali More",
    flag: null
  },
  {
    id: 130,
    from: "Barasat Station",
    to: "Kazipara",
    via: ["Barrackpore Trunk Road"],
    fareINR: 80,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Barasat Chapadali More",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 131,
    from: "Kazipara",
    to: "Belghoria Station",
    via: ["Barrackpore Trunk Road"],
    fareINR: 65,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 132,
    from: "Belghoria Station",
    to: "Agarpara",
    via: ["Barrackpore Trunk Road"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 133,
    from: "Agarpara",
    to: "Sodepur",
    via: ["Barrackpore Trunk Road"],
    fareINR: 50,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: "Sodepur Girja",
    flag: null
  },
  {
    id: 134,
    from: "Sodepur",
    to: "Barrackpore",
    via: ["Barrackpore Trunk Road"],
    fareINR: 75,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Sodepur Girja",
    toMatchedBusStop: "Barrackpore Chiria More",
    flag: null
  },
  {
    id: 135,
    from: "Barrackpore",
    to: "Palta",
    via: ["Barrackpore Trunk Road"],
    fareINR: 45,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: "Barrackpore Chiria More",
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 136,
    from: "Palta",
    to: "Naihati",
    via: ["Barrackpore Trunk Road"],
    fareINR: 60,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
  {
    id: 137,
    from: "Naihati",
    to: "Kanchrapara",
    via: ["Barrackpore Trunk Road"],
    fareINR: 55,
    fareSource: "user-provided (unverified against any centralized public source)",
    fromMatchedBusStop: null,
    toMatchedBusStop: null,
    flag: null
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { autoFares, officialTariff, estimateFare, busRouteStops };
}